# version: "3.9"

networks:
  mongo_net:
    driver: bridge

services:
  parser:
    build: .
    volumes:
      - ./app:/app
    command: python -u /app/bot.py
    networks:
      - mongo_net
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo_net
